import { BranchOfficeInfo } from "../interfaces/branch-office-info/branch-office-info.interface";

export const dataCoordinates:BranchOfficeInfo[] = [
  {
    name:  "Mi ubicacion",
    lat: 19.395210,
    lng: -99.230566,
    icon: "assets/icon/myLoc.png",
    uriImage: null,
    address:null,
    promotions:null,
    uriMap:null,
  },{
    name:  "Deli Café Constituyentes #2",
    lat: 19.395210,
    lng: -99.230566,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Constituyentes_2.JPG",
    address:"Cda. Madereros 1, Col. Lomas Altas",
    promotions: null,
    uriMap: "http://maps.google.com?q=19.395187,-99.230567",
  }, {
    name:  "Deli Café ITAM",
    lat: 19.344184,
    lng: -99.200411,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/ITAM.JPG",
    address: "Rio Hondo 3, Col. Progreso Tizapan",
    promotions: null,
    uriMap: "http://maps.google.com?q=Río+Hondo+3,+Progreso,+01080+Ciudad+de+México,+CDMX/",
  }, {
    name:  "Deli Café Gruta",
    lat: 19.325825,
    lng: -99.200122,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Gruta.JPG",
    address: "Cda. de Gruta 19, Col. Jardines del Pedregal",
    promotions: null,
    uriMap: "http://maps.google.com?q=Ruta+19,+Jardines+del+Pedregal,+01900+Ciudad+de+México,+CDMX/",
  }, {
    name:  "Deli Café Piaget",
    lat: 19.325139,
    lng: -99.222851,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Piaget.JPG",
    address: "San Jeronimo 1118, Col. San Jeronimo Lidice",
    promotions: null,
    uriMap: "http://maps.google.com?q=Av.+San+Jerónimo+1118,+San+Jerónimo+Lídice,+10200+Ciudad+de+México,+CDMX/",
  }, {
    name:  "Deli Café Dos Vistas",
    lat: 19.365449,
    lng: -99.252263,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Dos_Vistas.JPG",
    address: "Bernardo Quintana 400, Col. La Loma Santa Fe",
    promotions: null,
    uriMap: "http://maps.google.com?q=Av+Bernardo+Quintana+400,+Santa+Fe,+Zedec+Sta+Fé,+01219+Ciudad+de+México,+CDMX/",
  }, {
    name:  "Deli Café Corp. Chedraui",
    lat: 19.394032,
    lng: -99.236941,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Corp_Chedraui.JPG",
    address: "Constituyentes 1150, Col. Lomas Altas",
    promotions: null,
    uriMap: "http://maps.google.com?q=Av+Constituyentes+1150,+Lomas+Altas,+11950+Ciudad+de+México,+CDMX/",
  }, {
    name:  "Deli Café Colegio Francés",
    lat: 19.313453,
    lng: -99.208188,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Frances.JPG",
    address: "Colegio 330, Col. Jardines del Pedregal",
    promotions: null,
    uriMap: "http://maps.google.com?q=Colegio+330,+Jardines+del+Pedregal,+01900+Ciudad+de+México,+CDMX/",
  }, {
    name:  "Deli Café Boehringer",
    lat: 19.355284,
    lng: -99.115136,
    icon: "assets/icon/cafeLoc.svg",
    uriImage: "assets/img/branchoffices/Boheringer.JPG",
    address: "Maíz 49, Col. Xochimilco",
    promotions: null,
    uriMap: "http://maps.google.com?q=Maíz+49,+Santiago+Tepalcatlalpan,+16200+Ciudad+de+México,+CDMX/",
  }
];
